# Generated by Django 5.1 on 2024-09-03 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='computer_hardware',
            name='price',
            field=models.CharField(default=0, max_length=50),
        ),
        migrations.AddField(
            model_name='computer_hardware',
            name='quantity',
            field=models.CharField(default=0, max_length=50),
        ),
    ]
